/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationId = IDL.Nat;
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'underReview' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const FileId = IDL.Text;
export const Course = IDL.Variant({
  'arts' : IDL.Null,
  'engineering' : IDL.Null,
  'commerce' : IDL.Null,
  'science' : IDL.Null,
});
export const Application = IDL.Record({
  'id' : ApplicationId,
  'dob' : IDL.Text,
  'status' : ApplicationStatus,
  'applicant' : IDL.Principal,
  'marksheetFileId' : IDL.Opt(FileId),
  'fullName' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'previousQualification' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'photoFileId' : IDL.Opt(FileId),
  'phone' : IDL.Text,
  'course' : Course,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ApplicationInput = IDL.Record({
  'dob' : IDL.Text,
  'marksheetFileId' : IDL.Opt(FileId),
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'previousQualification' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'photoFileId' : IDL.Opt(FileId),
  'phone' : IDL.Text,
  'course' : Course,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getApplicationById' : IDL.Func(
      [ApplicationId],
      [IDL.Opt(Application)],
      ['query'],
    ),
  'getApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitApplication' : IDL.Func([ApplicationInput], [ApplicationId], []),
  'updateApplicationStatus' : IDL.Func(
      [ApplicationId, ApplicationStatus],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationId = IDL.Nat;
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'underReview' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const FileId = IDL.Text;
  const Course = IDL.Variant({
    'arts' : IDL.Null,
    'engineering' : IDL.Null,
    'commerce' : IDL.Null,
    'science' : IDL.Null,
  });
  const Application = IDL.Record({
    'id' : ApplicationId,
    'dob' : IDL.Text,
    'status' : ApplicationStatus,
    'applicant' : IDL.Principal,
    'marksheetFileId' : IDL.Opt(FileId),
    'fullName' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'previousQualification' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'photoFileId' : IDL.Opt(FileId),
    'phone' : IDL.Text,
    'course' : Course,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ApplicationInput = IDL.Record({
    'dob' : IDL.Text,
    'marksheetFileId' : IDL.Opt(FileId),
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'previousQualification' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'photoFileId' : IDL.Opt(FileId),
    'phone' : IDL.Text,
    'course' : Course,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getApplicationById' : IDL.Func(
        [ApplicationId],
        [IDL.Opt(Application)],
        ['query'],
      ),
    'getApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitApplication' : IDL.Func([ApplicationInput], [ApplicationId], []),
    'updateApplicationStatus' : IDL.Func(
        [ApplicationId, ApplicationStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };