/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : ApplicationId,
  'dob' : string,
  'status' : ApplicationStatus,
  'applicant' : Principal,
  'marksheetFileId' : [] | [FileId],
  'fullName' : string,
  'submittedAt' : bigint,
  'email' : string,
  'previousQualification' : string,
  'address' : string,
  'gender' : string,
  'photoFileId' : [] | [FileId],
  'phone' : string,
  'course' : Course,
}
export type ApplicationId = bigint;
export interface ApplicationInput {
  'dob' : string,
  'marksheetFileId' : [] | [FileId],
  'fullName' : string,
  'email' : string,
  'previousQualification' : string,
  'address' : string,
  'gender' : string,
  'photoFileId' : [] | [FileId],
  'phone' : string,
  'course' : Course,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'underReview' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type Course = { 'arts' : null } |
  { 'engineering' : null } |
  { 'commerce' : null } |
  { 'science' : null };
export type FileId = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getApplicationById' : ActorMethod<[ApplicationId], [] | [Application]>,
  'getApplications' : ActorMethod<[], Array<Application>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitApplication' : ActorMethod<[ApplicationInput], ApplicationId>,
  'updateApplicationStatus' : ActorMethod<
    [ApplicationId, ApplicationStatus],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];